// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHMlxZLF_-AAMA4fcWw64gjfOHHxel9NY',
    appId: '1:1047377611042:web:3ed5b3b553aad72cb77d7b',
    messagingSenderId: '1047377611042',
    projectId: 'fleetride-58204',
    authDomain: 'fleetride-58204.firebaseapp.com',
    databaseURL: 'https://fleetride-58204-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fleetride-58204.appspot.com',
    measurementId: 'G-56PRSDMF29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcskvIH4Tq89AACDUk1rcaRtmJ2YxNPHU',
    appId: '1:1047377611042:android:dee9c600e849c20bb77d7b',
    messagingSenderId: '1047377611042',
    projectId: 'fleetride-58204',
    databaseURL: 'https://fleetride-58204-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fleetride-58204.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAloirM_FRGojWIhXAx-MIrkIk25Psu-KE',
    appId: '1:1047377611042:ios:60bccb84f83189f7b77d7b',
    messagingSenderId: '1047377611042',
    projectId: 'fleetride-58204',
    databaseURL: 'https://fleetride-58204-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fleetride-58204.appspot.com',
    iosBundleId: 'com.example.fleetride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAloirM_FRGojWIhXAx-MIrkIk25Psu-KE',
    appId: '1:1047377611042:ios:60bccb84f83189f7b77d7b',
    messagingSenderId: '1047377611042',
    projectId: 'fleetride-58204',
    databaseURL: 'https://fleetride-58204-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fleetride-58204.appspot.com',
    iosBundleId: 'com.example.fleetride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHMlxZLF_-AAMA4fcWw64gjfOHHxel9NY',
    appId: '1:1047377611042:web:9080836e87e142b3b77d7b',
    messagingSenderId: '1047377611042',
    projectId: 'fleetride-58204',
    authDomain: 'fleetride-58204.firebaseapp.com',
    databaseURL: 'https://fleetride-58204-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fleetride-58204.appspot.com',
    measurementId: 'G-3NXS9XYQPW',
  );
}
